{{- if .Values.catalogue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-catalogue
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
spec:
  replicas: {{ .Values.catalogue.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: catalogue
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: catalogue
    spec:
      containers:
      - name: catalogue
        image: {{ tpl .Values.catalogue.image.repository . }}:{{ tpl .Values.catalogue.image.tag . }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.catalogue.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-catalogue
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
spec:
  type: {{ .Values.catalogue.service.type }}
  ports:
  - port: {{ .Values.catalogue.service.port }}
    targetPort: {{ .Values.catalogue.service.port }}
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
{{- end }}