{{- if .Values.voting.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-voting
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting
spec:
  replicas: {{ .Values.voting.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: voting
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: voting
    spec:
      containers:
      - name: voting
        image: {{ tpl .Values.voting.image.repository . }}:{{ tpl .Values.voting.image.tag . }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.voting.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-voting
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting
spec:
  type: {{ .Values.voting.service.type }}
  ports:
  - port: {{ .Values.voting.service.port }}
    targetPort: {{ .Values.voting.service.port }}
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: voting
{{- end }}