global:
  tag: latest

frontend:
  replicaCount: 3
  ingress:
    host: craftista.com

catalogue:
  replicaCount: 3

recommendation:
  replicaCount: 3

voting:
  replicaCount: 3

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  node-type: production

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - craftista
        topologyKey: kubernetes.io/hostname